# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='About_myself',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_myself',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
