# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
