# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
